<form action = '/blog/addBlog' method = 'post' class = 'm-5'>
  <!-- Title input -->
  <h3 class = 'text-center mb-5'>Write your blog</h3>
  <div class="form-outline mb-4" >
    <input type="text" name = 'title' class="form-control" />
    <label class="form-label" >Title</label>
  </div>

  <!-- Content input -->
  <div class="form-outline mb-4">
    <textarea class="form-control" name = 'content' rows="4"></textarea>
    <label class="form-label" >Write your blog</label>
  </div>

  <!-- Submit button -->
  <button type="submit" class="btn btn-primary btn-block mb-4">Add Blog</button>
</form>
