<div class="card mt-5 mb-3">
    <img class="card-img-top" src="https://mdbootstrap.com/img/new/standard/nature/184.jpg"
        alt="Card image cap" style="max-height: 200px;"
    >
    <div class="card-body">
        <?php
            $data = json_decode($data, true);
            echo "<small class=\"text-muted\"><strong>Blog ID:</strong>$data[id]</small>
                <h5 class=\"card-title\">$data[title]</h5>
                <p class=\"card-text\">$data[content]</p>
                <p class=\"card-text\"><small class=\"text-muted\">$data[date]</small></p>
                <h5><strong>Author:</strong>".$data['author']['name']."</h5>
                ";
        ?>
    </div>
</div>
<a href="/blog/" class = 'btn btn-secondary'>Go Back</a>
