<?php
$data = json_decode($data, true);
session_start();
?>
<header>
    <!-- Intro settings -->
    <style>
        #intro {
            /* Margin to fix overlapping fixed navbar */
            margin-top: 58px;
        }
        @media (max-width: 991px) {
            #intro {
                /* Margin to fix overlapping fixed navbar */
                margin-top: 45px;
            }
        }
    </style>
</header>
<!--Main layout-->
<main class="my-5">
    <div class="container">
        <!--Section: Content-->
        <section class="text-center">
            <a href="/blog/add" class='btn btn-success d-flex float-right'>Add New Blog</a>
            <h4 class="mb-5"><strong>Latest blogs</strong></h4>
            <div class="row">

                <?php
                foreach ($data as $key => $value) {
                    echo "<div class=\"col-lg-4 col-md-12 mb-4\">
                    <div class=\"card\">
                        <div class=\"bg-image hover-overlay ripple\" data-mdb-ripple-color=\"light\">
                            <img src=\"https://mdbootstrap.com/img/new/standard/nature/184.jpg\"
                                class=\"img-fluid\" alt=\"cover\"
                                />
                                <a href=\"#!\">
                                    <div class=\"mask\" style=\"background-color: rgba(251, 251, 251, 0.15);\"></div>
                                </a>
                            </div>
                            <div class=\"card-body\">
                                <h5 class=\"card-title\"><strong>$value[title]</strong></h5>
                                <p class=\"card-text\">$value[content]</p>
                                <p class=\"card-text\"><strong>Author : </strong>" . $value['author']['name'] . "</p>
                                <p class=\"card-text\"><strong>Date : </strong>$value[date]</p>
                                <a href=\"/blog/displaySingle?id=$value[id]\" class=\"btn btn-primary mx-1\">Read</a>";
                    if ($_SESSION['uid'] == $value['author']['id'] || $_SESSION['role'] == 'admin') {
                        echo "<a href=\"/blog/edit?id=$value[id]\" class=\"btn btn-danger mx-1\">Edit</a>";
                    }
                    echo "</div>
                        </div>
                    </div>";
                }
                ?>
            </div>
        </section>
        <!--Section: Content-->

        <!-- Pagination -->
        <nav class="my-4" aria-label="...">
            <ul class="pagination pagination-circle justify-content-center">
                <li class="page-item">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                </li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                </li>
            </ul>
        </nav>
    </div>
</main>
<!--Main layout-->

<!--Footer-->
<footer class="bg-light text-lg-start">
    <hr class="m-0" />
    <div class="text-center py-4 align-items-center">
        <p>Follow us on social media</p>
        <a href="#" class="btn btn-primary m-1" role="button" rel="nofollow">
            <i class="fab fa-youtube"></i>
        </a>
        <a href="#" class="btn btn-primary m-1" role="button" rel="nofollow">
            <i class="fab fa-facebook-f"></i>
        </a>
        <a href="#" class="btn btn-primary m-1" role="button" rel="nofollow">
            <i class="fab fa-twitter"></i>
        </a>
        <a href="#" class="btn btn-primary m-1" role="button" rel="nofollow">
            <i class="fab fa-github"></i>
        </a>
    </div>
</footer>
<!--Footer-->
